<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3t_backstretch"
 *
 * Auto generated by Extension Builder 2015-06-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Backstretch',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Elvis Tavasja',
	'author_email' => 'tavasja@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0 - 6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);