<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3t_backstretch"
 *
 * Auto generated by Extension Builder 2015-06-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Backstretch',
	'description' => 'Backstretch is a simple jQuery plugin that allows you to add a dynamically-resized, slideshow-capable background image to any page or element. The image will stretch to fit the page/element, and will automatically resize as the window/element size changes',
	'category' => 'plugin',
	'author' => 'Elvis Tavasja',
	'author_email' => 'info@w3development.net',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.5',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0 - 7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);