<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'W3D\\T3tBackstretch\\Controller\\ImageController' => $typo3InstallDir . 'typo3conf/ext/t3t_backstretch/Classes/Controller/ImageController.php',
    'W3D\\T3tBackstretch\\Domain\\Model\\Image' => $typo3InstallDir . 'typo3conf/ext/t3t_backstretch/Classes/Domain/Model/Image.php',
    'W3D\\T3tBackstretch\\Domain\\Repository\\ImageRepository' => $typo3InstallDir . 'typo3conf/ext/t3t_backstretch/Classes/Domain/Repository/ImageRepository.php',
);
